# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
name: CI

# WARNING! PLEASE READ BEFORE MAKING ANY CHANGES:
#
# This workflow is triggered on `pull_request_target` event,
# which makes it highly prone to security issues,
# as in this case we are executing untrusted, user-provided,
# potentially malicious code from pull requests in an environment
# that might contain overly permissive tokens or exposed secrets,
# if not implemented properly.
#
# Please only modify this file if you know what you're doing.

on:
  push:
    branches: [main, master]
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  ci:
    uses: asimov-modules/.github/.github/workflows/ci-rust.yaml@master
    secrets: inherit
    permissions:
      actions: read
      contents: read
      pull-requests: write
    with:
      building_toolchain: 1.88.0
      linux_dependencies: |
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo rm /var/lib/man-db/auto-update
        sudo apt-get install -y libc++-dev libc++abi-dev libgtk2.0-dev libatk1.0-dev libgtk-3-dev libxdo-dev
      macos_dependencies: |
        openssl_path=$(brew --prefix openssl@3)
        echo $openssl_path
        echo "$openssl_path/lib" >> $GITHUB_PATH
        echo "OPENSSL_ROOT_DIR=$openssl_path" >> $GITHUB_ENV
