# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
name: Release

# Trigger on any tag creation:
on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    name: Build and release
    uses: asimov-modules/.github/.github/workflows/build-and-release-rust-module.yaml@master
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      update_homebrew_tap: true
      update_scoop_bucket: true
      tweet_release: true
      depends_on_openssl: true
      linux_dependencies: |
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo rm /var/lib/man-db/auto-update
        sudo apt-get install -y libc++-dev libc++abi-dev libgtk2.0-dev libatk1.0-dev libgtk-3-dev libxdo-dev
